services:
  telegram-bot-api-majorro:
    image: aiogram/telegram-bot-api:latest
    container_name: telegram-bot-api-majorro
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${TELEGRAM_API_DATA_DIR_MAJORRO}:/var/lib/telegram-bot-api
      - ${LOCAL_TEMP_DIR}:${CONTAINER_TEMP_DIR}
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID_MAJORRO}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH_MAJORRO}
      - TELEGRAM_LOCAL=1
      - TELEGRAM_VERBOSITY=2

  telegram-bot-api-panya:
    image: aiogram/telegram-bot-api:latest
    container_name: telegram-bot-api-panya
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${TELEGRAM_API_DATA_DIR_PANYA}:/var/lib/telegram-bot-api
      - ${LOCAL_TEMP_DIR}:${CONTAINER_TEMP_DIR}
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID_PANYA}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH_PANYA}
      - TELEGRAM_LOCAL=1
      - TELEGRAM_VERBOSITY=2

  doujin-music-reposter:
    image: ghcr.io/majorro/doujin-music-reposter:latest
    container_name: doujin-music-reposter
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${LOCAL_DMR_DATABASE_DIR}:${CONTAINER_DMR_DATABASE_DIR}
      - ${LOCAL_TEMP_DIR}:${CONTAINER_TEMP_DIR}
    depends_on:
      telegram-bot-api-majorro:
        condition: service_healthy
      telegram-bot-api-panya:
        condition: service_healthy