name: CD

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create dummy .env
        run: |          
          cat > .env << EOF
          LOCAL_TEMP_DIR=/
          CONTAINER_TEMP_DIR=/
          LOCAL_DMR_DATABASE_DIR=/
          CONTAINER_DMR_DATABASE_DIR=/
          TELEGRAM_API_DATA_DIR_MAJORRO=/
          TELEGRAM_API_DATA_DIR_PANYA=/
          EOF

      - name: Build images
        run: docker compose --profile app build

      - name: Push images to ghcr.io
        run: docker compose --profile app push